import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { BusFiHeroSection } from "@/components/bus-fi/hero-section";
import { BusFiOverviewSection } from "@/components/bus-fi/overview-section";
import { BusFiGoalsSection } from "@/components/bus-fi/goals-section";
import { BusFiSpecificationsSection } from "@/components/bus-fi/specifications-section";
import { BusFiKeyFeaturesSection } from "@/components/bus-fi/key-features-section";
import { BusFiReputationSystemSection } from "@/components/bus-fi/reputation-system-section";
import { BusFiTokenomicsSection } from "@/components/bus-fi/tokenomics-section";
import { BusFiMilestonesSection } from "@/components/bus-fi/milestones-section";
import { BusFiDemoSection } from "@/components/bus-fi/demo-section";
import { BusFiFAQSection } from "@/components/bus-fi/faq-section";
import { CollapsibleSection } from "@/components/bitpact/shared/collapsible-section";
import { StructuredData } from "@/components/seo/structured-data";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Bus-Fi - Decentralized Bus Network Funding | CryptoSI",
  description: "Bus-Fi is a decentralized crowdfunding platform built on the Hedera network, designed to finance the acquisition and operation of bus networks in underserved African communities. Funders receive NFTs and share in bus operation profits.",
  keywords: ["DeFi", "Real-World Assets", "Hedera", "Transportation", "Africa", "NFT", "Crowdfunding", "Financial Inclusion"],
  openGraph: {
    type: 'article',
    title: 'Bus-Fi - Decentralized Bus Network Funding',
    description: 'Bus-Fi is a decentralized crowdfunding platform built on the Hedera network, designed to finance the acquisition and operation of bus networks in underserved African communities.',
    url: 'https://cryptosi.dao/ideas/bus-fi',
    images: [
      {
        url: 'https://cryptosi.dao/images/busfitrans.png',
        width: 1200,
        height: 630,
        alt: 'Bus-Fi - Decentralized Bus Network Funding',
        type: 'image/png',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Bus-Fi - Decentralized Bus Network Funding',
    description: 'Bus-Fi is a decentralized crowdfunding platform built on the Hedera network, designed to finance the acquisition and operation of bus networks in underserved African communities.',
    images: ['https://cryptosi.dao/images/busfitrans.png'],
  },
  alternates: {
    canonical: 'https://cryptosi.dao/ideas/bus-fi',
  },
};

export default function BusFiPage() {
  const breadcrumbData = [
    { name: 'Home', url: 'https://cryptosi.dao' },
    { name: 'Ideas', url: 'https://cryptosi.dao/ideas' },
    { name: 'Bus-Fi', url: 'https://cryptosi.dao/ideas/bus-fi' },
  ];

  const projectData = {
    title: 'Bus-Fi - Decentralized Bus Network Funding',
    description: 'Bus-Fi is a decentralized crowdfunding platform built on the Hedera network, designed to finance the acquisition and operation of bus networks in underserved African communities. Funders receive NFTs as proof of investment and share in the profits generated by bus operations.',
    url: 'https://cryptosi.dao/ideas/bus-fi',
    image: 'https://cryptosi.dao/images/busfitrans.png',
    datePublished: '2024-01-01',
    dateModified: new Date().toISOString(),
    tags: ['DeFi', 'Real-World Assets', 'Hedera', 'Transportation', 'Africa', 'NFT', 'Crowdfunding', 'Financial Inclusion'],
  };

  return (
    <div className="flex flex-col min-h-screen">
      <StructuredData type="breadcrumb" data={{ breadcrumbs: breadcrumbData }} />
      <StructuredData type="project" data={projectData} />
      <Header />
      <main className="flex-1">
        <BusFiHeroSection />
        
        <CollapsibleSection
          title="🪙 Overview"
          subtitle="Bus-Fi is a decentralized crowdfunding platform built on the Hedera network, designed to finance the acquisition and operation of bus networks in underserved African communities. Funders receive NFTs as proof of investment and share in the profits generated by bus operations."
          defaultExpanded={true}
        >
          <BusFiOverviewSection />
        </CollapsibleSection>
        
        <CollapsibleSection
          title="🎯 Goals"
          subtitle="Bus-Fi is built on fundamental goals that address the core challenges in transportation infrastructure and financial inclusion across Africa"
          className="bg-muted/30"
        >
          <BusFiGoalsSection />
        </CollapsibleSection>
        
        <CollapsibleSection
          title="⚙️ Specifications"
          subtitle="Technical specifications designed for maximum impact, security, and real-world integration"
        >
          <BusFiSpecificationsSection />
        </CollapsibleSection>
        
        <CollapsibleSection
          title="⚡ Key Features"
          subtitle="Innovative features that set Bus-Fi apart from traditional funding mechanisms"
          className="bg-muted/30"
        >
          <BusFiKeyFeaturesSection />
        </CollapsibleSection>
        
        <CollapsibleSection
          title="📊 Reputation System"
          subtitle="The on-chain reputation mechanism that builds trust and enables sustainable financing"
        >
          <BusFiReputationSystemSection />
        </CollapsibleSection>
        
        <CollapsibleSection
          title="💰 Tokenomics"
          subtitle="Fueling growth and returns through innovative NFT-based investment model"
          className="bg-muted/30"
        >
          <BusFiTokenomicsSection />
        </CollapsibleSection>
        
        <CollapsibleSection
          title="🚀 Milestones"
          subtitle="Our roadmap to revolutionizing transportation finance in Africa"
        >
          <BusFiMilestonesSection />
        </CollapsibleSection>
        
        <CollapsibleSection
          title="🎮 Interactive Demo"
          subtitle="Experience the Bus-Fi investment process step by step"
          className="bg-gradient-to-br from-primary/5 to-secondary/5"
          defaultExpanded={true}
        >
          <BusFiDemoSection />
        </CollapsibleSection>
        
        <CollapsibleSection
          title="Frequently Asked Questions"
          subtitle="Common questions about Bus-Fi answered"
          className="bg-muted/30"
        >
          <BusFiFAQSection />
        </CollapsibleSection>
      </main>
      <Footer />
    </div>
  );
}