"use client";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Lightbulb, ArrowRight, Users, ChevronDown, ChevronUp, Code, TrendingUp, DollarSign } from "lucide-react";
import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { motion } from "framer-motion";

type Idea = {
  title: string;
  description: string;
  category: string;
  status: string;
  isDeveloperCard?: boolean;
};

const ideas: Idea[] = [
  {
    title: "🪙 BitPact",
    description: "BitPact is a decentralized P2P Bitcoin protocol where trades are more than transactions — they're pacts. Enforced by multisig, protected by bonded arbiters, and immortalized through immutable reputation, BitPact brings honor, transparency, and cryptographic justice to peer-to-peer exchange. Built for sovereign individuals, BitPact is trustless by design and powered by the ethos of Bitcoin.",
    category: "Bitcoin",
    status: "Development",
  },
  {
    title: "MirrorVault",
    description: "MirrorVault is a decentralized, non-custodial copy-trading protocol built for Ethereum and EVM-compatible networks. It allows followers to deposit into smart-contract vaults managed by verified traders ('Managers') whose trades are automatically mirrored on-chain in real time. By combining secure vault architecture, transparent performance tracking, and an on-chain reputation layer called Aegis Score, MirrorVault creates a fully trustless ecosystem for aligned, transparent trading between experts and their communities. With weekly profit crystallization, verifiable returns, and non-custodial control, MirrorVault redefines copy trading for the Web3 era.",
    category: "DeFi",
    status: "Development",
  },
  {
    title: "KIN Protocol",
    description: "KIN Protocol is a decentralized, undercollateralized lending platform designed to unlock trust-based lending in DeFi. Built on a tri-party model—Borrowers, Lenders, and Vouchers—KIN leverages on-chain mechanisms like vouch staking, slashing penalties, and NFT-backed loan contracts to create a transparent, flexible, and community-driven ecosystem.",
    category: "DeFi",
    status: "Research",
  },
  {
    title: "Hedera Bus-FI",
    description: "This project proposes a decentralized crowdfunding platform built on the Hedera network, designed to finance the acquisition and operation of bus networks in underserved African communities. It directly addresses the need for improved public transportation infrastructure while simultaneously democratizing investment opportunities and enabling equitable access to decentralized financial tools. Funders will receive Non-Fungible Tokens (NFTs) as proof of their investment, and a portion of the profits generated by the bus operations will be automatically distributed back to these NFT holders. This initiative aims to be an impactful decentralized application (dApp) that drives real-world adoption of Web3 technologies in Africa.",
    category: "Impact",
    status: "Planning",
  },
];

const developerCard: Idea = {
  title: "💻 Partner With Us",
  description: "Earn up to 50% of dApp revenues by building these projects. Get DAO support, technical resources, and long-term partnership opportunities.",
  category: "Developers",
  status: "Open",
  isDeveloperCard: true,
};

export function IdeasSection() {
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <section id="ideas" className="w-full py-12 md:py-24 lg:py-32 bg-muted/30">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="flex items-center justify-center gap-4">
            <div className="flex items-center gap-2">
              <Lightbulb className="w-8 h-8 text-primary" />
              <h2 className="text-3xl font-headline tracking-tighter sm:text-5xl">Ideas</h2>
            </div>
            <Button variant="ghost" size="icon" onClick={() => setIsExpanded(!isExpanded)}>
              {isExpanded ? <ChevronUp className="h-6 w-6" /> : <ChevronDown className="h-6 w-6" />}
              <span className="sr-only">{isExpanded ? 'Collapse section' : 'Expand section'}</span>
            </Button>
          </div>
          {isExpanded && (
            <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Explore our upcoming initiatives and concepts. These are the projects we're currently developing or planning to bring to the CryptoSI ecosystem.
            </p>
          )}
        </div>
        
        {isExpanded && (
          <div className="mx-auto grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 pt-12">
            {[...ideas, developerCard].map((idea, index) => (
              <Card key={index} className={`overflow-hidden transform transition-all duration-300 hover:scale-105 hover:shadow-2xl hover:shadow-primary/40 h-full flex flex-col ${idea.isDeveloperCard ? 'bg-gradient-to-br from-primary/10 to-secondary/10 border-2 border-primary/30' : ''}`}>
                <CardHeader className="p-6 pb-4">
                  <div className="flex items-center justify-between mb-4">
                    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${idea.isDeveloperCard ? 'bg-gradient-to-r from-primary/20 to-secondary/20 text-primary' : 'bg-primary/10 text-primary'}`}>
                      {idea.category}
                    </span>
                    <span className={`text-xs ${idea.isDeveloperCard ? 'text-primary font-semibold' : 'text-muted-foreground'}`}>{idea.status}</span>
                  </div>
                  <CardTitle className="text-xl font-bold font-body">{idea.title}</CardTitle>
                </CardHeader>
                <CardContent className="p-6 pt-0 flex flex-col flex-grow">
                  <CardDescription className="mb-6 flex-grow">
                    {idea.description}
                  </CardDescription>
                  {idea.title === "🪙 BitPact" && (
                    <div className="mb-6 relative w-full aspect-video rounded-lg overflow-hidden bg-black shadow-lg">
                      <motion.div
                        className="absolute inset-0 rounded-lg border-2 border-primary/20 pointer-events-none"
                        animate={{
                          opacity: [0.5, 1, 0.5],
                        }}
                        transition={{
                          duration: 3,
                          repeat: Infinity,
                          ease: "easeInOut"
                        }}
                      />
                      <iframe
                        width="560"
                        height="315"
                        src="https://www.youtube.com/embed/JGZOwDFRQ-s"
                        title="BitPact Demo"
                        frameBorder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowFullScreen
                        className="w-full h-full"
                      ></iframe>
                    </div>
                  )}
                  {idea.title === "MirrorVault" && (
                    <div className="mb-6 relative w-full aspect-video rounded-lg overflow-hidden bg-black shadow-lg">
                      <motion.div
                        className="absolute inset-0 rounded-lg border-2 border-primary/20 pointer-events-none"
                        animate={{
                          opacity: [0.5, 1, 0.5],
                        }}
                        transition={{
                          duration: 3,
                          repeat: Infinity,
                          ease: "easeInOut"
                        }}
                      />
                      <iframe
                        width="560"
                        height="315"
                        src="https://www.youtube.com/embed/zisitRjurm8"
                        title="MirrorVault Demo"
                        frameBorder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowFullScreen
                        className="w-full h-full"
                      ></iframe>
                    </div>
                  )}
                  {idea.title === "KIN Protocol" && (
                    <div className="mb-6 relative w-full aspect-video rounded-lg overflow-hidden bg-black shadow-lg">
                      <motion.div
                        className="absolute inset-0 rounded-lg border-2 border-primary/20 pointer-events-none"
                        animate={{
                          opacity: [0.5, 1, 0.5],
                        }}
                        transition={{
                          duration: 3,
                          repeat: Infinity,
                          ease: "easeInOut"
                        }}
                      />
                      <iframe
                        width="560"
                        height="315"
                        src="https://www.youtube.com/embed/LxmXhV88SdY"
                        title="KIN Protocol Demo"
                        frameBorder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowFullScreen
                        className="w-full h-full"
                      ></iframe>
                    </div>
                  )}
                  {idea.title === "Hedera Bus-FI" && (
                    <div className="mb-6 relative w-full aspect-video rounded-lg overflow-hidden bg-black shadow-lg">
                      <motion.div
                        className="absolute inset-0 rounded-lg border-2 border-primary/20 pointer-events-none"
                        animate={{
                          opacity: [0.5, 1, 0.5],
                        }}
                        transition={{
                          duration: 3,
                          repeat: Infinity,
                          ease: "easeInOut"
                        }}
                      />
                      <iframe
                        width="560"
                        height="315"
                        src="https://www.youtube.com/embed/xJSgzBco1Jc"
                        title="Bus-Fi Demo"
                        frameBorder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowFullScreen
                        className="w-full h-full"
                      ></iframe>
                    </div>
                  )}
                  
                  {/* Developer Card Special Content */}
                  {idea.isDeveloperCard && (
                    <div className="mb-6 space-y-4">
                      <div className="grid grid-cols-3 gap-2 text-center">
                        <div className="p-2 bg-background/50 rounded">
                          <DollarSign className="w-4 h-4 text-green-500 mx-auto mb-1" />
                          <div className="text-xs font-bold">50%</div>
                          <div className="text-xs text-muted-foreground">Revenue Share</div>
                        </div>
                        <div className="p-2 bg-background/50 rounded">
                          <Code className="w-4 h-4 text-blue-500 mx-auto mb-1" />
                          <div className="text-xs font-bold">4+</div>
                          <div className="text-xs text-muted-foreground">Projects</div>
                        </div>
                        <div className="p-2 bg-background/50 rounded">
                          <TrendingUp className="w-4 h-4 text-purple-500 mx-auto mb-1" />
                          <div className="text-xs font-bold">∞</div>
                          <div className="text-xs text-muted-foreground">Duration</div>
                        </div>
                      </div>
                    </div>
                  )}
                  
                  <div className="flex gap-3">
                    {!idea.isDeveloperCard ? (
                      <>
                        <Button variant="outline" className="flex-1" asChild>
                          <Link href={idea.title === "🪙 BitPact" ? "/ideas/bitpact" : idea.title === "MirrorVault" ? "/ideas/mirrorvault" : idea.title === "KIN Protocol" ? "/ideas/kin-protocol" : idea.title === "Hedera Bus-FI" ? "/ideas/bus-fi" : "#"}>
                            <ArrowRight className="w-4 h-4 mr-2" />
                            More Info
                          </Link>
                        </Button>
                        <Button className="flex-1" asChild>
                          <Link href="/developers">
                            <Users className="w-4 h-4 mr-2" />
                            Join as Dev
                          </Link>
                        </Button>
                      </>
                    ) : (
                      <Button className="w-full" asChild>
                        <Link href="/developers">
                          <Code className="w-4 h-4 mr-2" />
                          Learn About Partnerships
                        </Link>
                      </Button>
                    )}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </div>
    </section>
  );
}